### ISSUE TITLE
[popovers]: components break when initialized with `open="true"`

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#10327]
### Bug Description

All popover components break if they're initialized with `open="true"`. This is very problematic for React users, as it's common there to conditional render components.

The example below is created with React, because it's easier implementing conditional rendering this way. If you require a example without React, please let me know.

Additionally, our `Modals` class no longer functions correctly without a workaround that involves using `requestAnimationFrame` to delay when the `open` prop is set. [Here you can find the workaround](https://github.com/SAP/ui5-webcomponents-react/blob/c7c2db2113c2cc744587b6851e29d0345d8f902e/packages/main/src/components/Modals/index.tsx#L223-L238). If you have a better approach to address this, please share it with us, as we cannot update our wrapper to the latest ui5wc version without this workaround.

### Affected Component

all popover components

### Isolated Example

https://stackblitz.com/edit/github-rxurcs-qdpwtf?file=src%2FApp.tsx,src%2Fmain.tsx

### Steps to Reproduce

1. Go to [StackBlitz](https://stackblitz.com/edit/github-rxurcs-qdpwtf?file=src%2FApp.tsx,src%2Fmain.tsx)
2. Try to close the opened popover via ESC press or by clicking anywhere else.
3. See that nothing happens.
4. Open the first popover by pressing the button and then try to close it again.
5. See that nothing happens.

### Priority

Very High

### UI5 Web Components Version

2.5.0

### Browser

Chrome

### Organization

UI5WCR

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Could you please check?

**Comment by TeodorTaushanov** [comment]
Hi @Lukas742, the issue is fixed in the main branch.

**Comment by nnaydenow** [comment]
Hi @TeodorTaushanov,

The issue is still reproducible with the fix.

**Comment by Lukas742** [comment]
Hi @TeodorTaushanov 

unfortunately the issue was only fixed for the `Popover` component, not other components using and exposing the popover API:

https://stackblitz.com/edit/github-rxurcs-53jnmt1a?file=src%2FApp.tsx,package.json

I didn't test all popover components, but I would assume that all of them have the same problem.
