### ISSUE TITLE
input field does not accept SPACE when becomes a child of ui5-table-cell

### ISSUE THREAD

**Issue by randolf-alegre** [SAP/ui5-webcomponents#3436]
Input field does not accept SPACE when place within the ui5-table-cell web component. When you start typing and press the space bar space is not displayed. To double-check the value, inspect the input element and see the value attribute.

Expected Behavior:
Input field should accept SPACE.

Steps to Reproduce:
1. Create a new ui5-table element.
2. add ui5-table-column.
3. add ui5-table-row.
4. Within the ui5-table-row, add ui5-table-cell.
5. Within the ui5-table-cell add a ui5-input element.
6. Start typing on the input field.

Sample:
https://codesandbox.io/s/practical-villani-s6w4f?file=/index.html

### **Context**
- UI5 Web Components version: v1.0.0-rc.14
- Browser: Google Chrome
- Affected component: ui5-table, ui5-table-row, ui5-table-cell

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

**Comment by gmkv** [comment]
Hi @randolf-alegre 
We recently had an issue for the same use case - #3390, which is already fixed, so you will be able to consume the fix in the next release of the library!
Thanks for reporting the issue.
Regards,
Georgi

**Comment by kotmiilawrence** [comment]
Hi @gmkv
The issue still persists when nested ui5-input element under ui5-table and ui5-table-row. I believe is due to the keydown handler under TableRow.js is still preventing space entry.

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-rl 
Could you take a look at this issue with the input inside a table row?

Regards,
Georgi

**Comment by gmkv** [comment]
@kotmiilawrence I believe this issue persists because the new version of the library hasn't been released yet.

**Comment by niyap** [comment]
Hello @randolf-alegre,

Thanks for sharing your findings!

As Georgi has mentioned, the issue is already reported #3390  and fixed with the following change https://github.com/SAP/ui5-webcomponents/pull/3393 

Please, wait for the next release and check again.

Kind Regards,
Niya
