### ISSUE TITLE
[MultiInput]: after input is empty the first render of token(s) always hide token(s) under "... More" caption

### ISSUE THREAD

**Issue by gagarin880120** [SAP/ui5-webcomponents#6964]
### Describe the bug

After MultiInput is empty and we choose some items to get tokens inside the MultiInput, the first render shows always caption "n More", where n is number of items(tokens). After we add some more tokens, we will saw normal behavior: if token(s) can be shown (based on their size - text's inside token length) - they are, if not - we see "... More" caption. If we remove all tokens and then try to repeat first step - we also will see "... More" caption (it doesn't matter how much are tokens or their size), instead of normal behaviour.

### Isolated Example

https://codesandbox.io/p/sandbox/gracious-http-g3xrwm?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A50%2C%22endLineNumber%22%3A33%2C%22startColumn%22%3A50%2C%22startLineNumber%22%3A33%7D%5D

### Reproduction steps

1. go to isolated example
2. press "Add" button
3. see "1 More"
4. press "Add" button one more time
5. see one token shown normally and second hided under "1 More" caption
6. press "Clear" button
7. press "Add" button
8. see "1 More" caption instead of see the first token normally, because we know from step 5, that it can be shown (size allows)

### Expected Behaviour

Tokens shows normally, based on their sizes, always.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/44781670/234858811-728ad1c6-ffba-4a03-8f5c-905fd9b2f6cc.png)
![image](https://user-images.githubusercontent.com/44781670/234858900-fe4ea78a-e613-4f45-9ef5-24504e3b5958.png)

### UI5 Web Components for React Version

1.8.1

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Operating System

Windows 10

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Okiana** [comment]
Hello colleagues,

I am releasing this incident since I have no more time to work on it. In the previous comments you can find isolation of the issue. Here is also my isolated scenario on which I've investigated https://codesandbox.io/s/ui5-webcomponents-forked-2z7ym6?file=/src/index.js

Kind regards,
Evdokia

**Comment by niyap** [comment]
Hello @gagarin880120, 

The issue is fixed in the latest release.

Kind Regards,
Niya

**Comment by gagarin880120** [comment]
> Hello @gagarin880120,
> 
> The issue is fixed in the latest release.
> 
> Kind Regards, Niya

No, it is not fixed. Please open codesandbox and check. Thank You!
