### ISSUE TITLE
[Input]: Safari ValueStateMessage causes blur

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#7960]
### Bug Description

When the Input ValueStateMessage is triggered by focusing the Input, it causes a blur and the ValueStateMessage is still visible.
This interrupts the usage as the Input is no longer focused.
The input still can be used because the ValueStateMessage is still open after the blur.

### Affected Component

ui5-input

### Expected Behaviour

ValueStateMessage should not cause blur when shown.

### Steps to Reproduce

1. Safari Version 17.1 (19616.2.9.11.7) 
2. https://sap.github.io/ui5-webcomponents/playground/?path=/story/main-input--value-state-message
3. Tab into the input
Observe: ValueStateMessage is visible, but focus was blurred
4. Tab into the input again
Observe: ValueStateMessage is visible and focus is in input

### Priority

Medium

### UI5 Web Components Version

1.18.0, 1.19.1, 1.20.0

### Browser

Safari

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

The value state popup appears for the input field:
<img width="353" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/15860295/35226106-f1e2-4fa8-8bea-38c51a818271">

Best regards,
Boyan

**Comment by MapTo0** [comment]
Possible regression: https://github.com/SAP/ui5-webcomponents/pull/7870

**Comment by ilhan007** [comment]
Hello @JarrettChan can you retest, we have merged and released a fix with 1.20.1
https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/story/main-input--value-state-message

**Comment by JarrettChan** [comment]
Hi @ilhan007,
The popover position looks good, but that is not my issue.
The issue I reported is that when you focus an Input with ValueStateMessage in Safari, it immediately blurs.
This is not fixed.

**Comment by petyabegovska** [comment]
Hi @JarrettChan,

Can you provide a screenshot of the blurred state?

Thanks and best regards,
Petya

**Comment by MapTo0** [comment]
Snippet to reproduce this with a popover only:

```html
<input id="opener" />
<ui5-popover id="popup" _disable-initial-focus></ui5-popover>

<script>
  const opener = document.getElementById("opener");

  opener.addEventListener("focusin", event => {
    document.getElementById("popup").showAt(opener, true);
  });

  opener.addEventListener("blur", event => {
    console.log("=========== BLUR =========");
  });
</script>
```

**Comment by kskondov** [comment]
Hello @JarrettChan and @MapTo0 as I was not able to reproduce this issue can you confirm that it is still reproducible on your side?

Best Regards

**Comment by MapTo0** [comment]
I am not able to reproduce it as well. Maybe Apple did some changes @JarrettChan how about you?

**Comment by kskondov** [comment]
After feedback from @MapTo0  and @JarrettChan I am closing this issue as not reproducible
