### ISSUE TITLE
[ui5-resposive-popover]: the responsive popover is not centered in rtl direction and existing scroll bar

### ISSUE THREAD

**Issue by iva-sap** [SAP/ui5-webcomponents#9966]
### Bug Description

ui5-resposive-popover is not centered in cases there is a scroll bar that changes its position on direction - RTL. The issue is reproducible on Mac if the appearance of the scroll bar is set to be always shown. 

### Affected Component

ui5-resposive-popover

### Expected Behaviour

ui5-resposive-popover should be centered.

### Isolated Example

[Playground example](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKVwiPlxuICAgIDxzdHlsZT5cbiAgICAgICAgYm9keSB7XG4gICAgICAgICAgICBoZWlnaHQ6IDQyMHB4O1xuICAgICAgICB9XG5cbiAgICAgICAgLnBvcG92ZXItY29udGVudCB7XG4gICAgICAgICAgICBkaXNwbGF5OiBmbGV4O1xuICAgICAgICAgICAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcbiAgICAgICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuICAgICAgICB9XG5cbiAgICAgICAgLnBvcG92ZXItZm9vdGVyIHtcbiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtZW5kO1xuICAgICAgICAgICAgd2lkdGg6IDEwMCU7XG4gICAgICAgICAgICBhbGlnbi1pdGVtczogY2VudGVyO1xuICAgICAgICAgICAgcGFkZGluZzogMC41cmVtIDA7XG4gICAgICAgIH1cblxuICAgICAgICAuY2VudGVyIHtcbiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcbiAgICAgICAgICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gICAgICAgICAgICBoZWlnaHQ6IDEwMCU7XG4gICAgICAgICAgICB3aWR0aDogMTAwJTtcbiAgICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuXG5cbiAgICA8ZGl2IGNsYXNzPVwiY2VudGVyXCI-XG4gICAgICAgIDx1aTUtYnV0dG9uIGlkPVwiYnRuMVwiPk9wZW48L3VpNS1idXR0b24-XG4gICAgPC9kaXY-XG4gICBcbiAgICA8dWk1LXJlc3BvbnNpdmUtcG9wb3ZlciAgaWQ9XCJyZXNwUG9wb3ZlcjFcIiBvcGVuZXI9XCJidG4xXCIgaGVhZGVyLXRleHQ9XCJOZXdzbGV0dGVyIHN1YnNjcmlwdGlvblwiIHBsYWNlbWVudD1cIkJvdHRvbVwiIGhvcml6b250YWxBbGlnbj1cIkNlbnRlclwiPlxuICAgICAgICA8ZGl2IGNsYXNzPVwicG9wb3Zlci1jb250ZW50XCI-XG4gICAgICAgICAgICA8dWk1LWxhYmVsIGZvcj1cImVtYWlsSW5wdXRcIiByZXF1aXJlZCBzaG93LWNvbG9uPkVtYWlsPC91aTUtbGFiZWw-XG4gICAgICAgICAgICA8dWk1LWlucHV0IGlkPVwiZW1haWxJbnB1dFwiIHN0eWxlPVwibWluLXdpZHRoOiAxNTBweDtcIiBwbGFjZWhvbGRlcj1cIkVudGVyIEVtYWlsXCI-PC91aTUtaW5wdXQ-XG4gICAgICAgICAgICA8dWk1LWxhYmVsPk5vdGU6IElmIHlvdSBvcGVuIHRoZSBwYWdlIGluIG1vYmlsZSwgYSBkaWFsb2cgd291bGQgYmUgZGlzcGxheWVkLjwvdWk1LWxhYmVsPlxuICAgICAgICA8L2Rpdj5cblxuICAgICAgICA8ZGl2IHNsb3Q9XCJmb290ZXJcIiBjbGFzcz1cInBvcG92ZXItZm9vdGVyXCI-XG4gICAgICAgICAgICA8dWk1LWJ1dHRvbiBpZD1cImNsb3NlUG9wb3ZlckJ1dHRvblwiIGRlc2lnbj1cIkVtcGhhc2l6ZWRcIj5TdWJzY3JpYmU8L3VpNS1idXR0b24-XG4gICAgICAgIDwvZGl2PlxuICAgIDwvdWk1LXJlc3BvbnNpdmUtcG9wb3Zlcj5cblxuICAgIDx1aTUtcmVzcG9uc2l2ZS1wb3BvdmVyIGlkPVwicmVzcFBvcG92ZXIyXCIgb3BlbmVyPVwiYnRuMlwiIGhlYWRlci10ZXh0PVwiTmV3c2xldHRlciBzdWJzY3JpcHRpb25cIiBwbGFjZW1lbnQ9XCJTdGFydFwiPlxuICAgICAgICA8ZGl2IGNsYXNzPVwicG9wb3Zlci1jb250ZW50XCI-XG4gICAgICAgICAgICA8dWk1LWxhYmVsIGZvcj1cImVtYWlsSW5wdXRcIiByZXF1aXJlZCBzaG93LWNvbG9uPkVtYWlsPC91aTUtbGFiZWw-XG4gICAgICAgICAgICA8dWk1LWlucHV0IGlkPVwiZW1haWxJbnB1dFwiIHN0eWxlPVwibWluLXdpZHRoOiAxNTBweDtcIiBwbGFjZWhvbGRlcj1cIkVudGVyIEVtYWlsXCI-PC91aTUtaW5wdXQ-XG4gICAgICAgICAgICA8dWk1LWxhYmVsPk5vdGU6IElmIHlvdSBvcGVuIHRoZSBwYWdlIGluIG1vYmlsZSwgYSBkaWFsb2cgd291bGQgYmUgZGlzcGxheWVkLjwvdWk1LWxhYmVsPlxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdiBzbG90PVwiZm9vdGVyXCIgY2xhc3M9XCJwb3BvdmVyLWZvb3RlclwiPlxuICAgICAgICAgICAgPHVpNS1idXR0b24gaWQ9XCJjbG9zZVBvcG92ZXJCdXR0b25cIiBkZXNpZ249XCJFbXBoYXNpemVkXCI-U3Vic2NyaWJlPC91aTUtYnV0dG9uPlxuICAgICAgICA8L2Rpdj5cbiAgICA8L3VpNS1yZXNwb25zaXZlLXBvcG92ZXI-XG4gIFxuICA8ZGl2IHN0eWxlPVwiaGVpZ2h0OiAxMDAwcHg7XCI-PC9kaXY-XG5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L1Jlc3BvbnNpdmVQb3BvdmVyLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9CdXR0b24uanNcIjtcbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0xhYmVsLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9JbnB1dC5qc1wiO1xuXG5jb25zdCBidG4xID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJidG4xXCIpO1xuY29uc3QgcmVzcFBvcG92ZXIxID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJyZXNwUG9wb3ZlcjFcIik7XG5jb25zdCBidG4yID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJidG4yXCIpO1xuY29uc3QgcmVzcFBvcG92ZXIyID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJyZXNwUG9wb3ZlcjJcIik7XG5cbmJ0bjEuYWRkRXZlbnRMaXN0ZW5lcihcImNsaWNrXCIsICgpID0-IHtcblx0cmVzcFBvcG92ZXIxLm9wZW4gPSAhcmVzcFBvcG92ZXIxLm9wZW47XG59KTtcbmJ0bjIuYWRkRXZlbnRMaXN0ZW5lcihcImNsaWNrXCIsICgpID0-IHtcblxuXHRyZXNwUG9wb3ZlcjIub3BlbiA9ICFyZXNwUG9wb3ZlcjIub3Blbjtcbn0pOyJ9fQ)

### Steps to Reproduce

1. Open the isolated example
2. Change the dir to rtl of the body element of the "Project preview" iframe in dev tools
3. Click on btn1

### Log Output, Stack Trace or Screenshots

<img width="1676" alt="Screenshot 2024-10-01 at 17 11 49" src="https://github.com/user-attachments/assets/c2937fca-f0e0-4388-a2b3-073f859f881e">

If the overflow is set to hidden in the body element then the responsive popover is positioned properly.

<img width="1676" alt="Screenshot 2024-10-01 at 17 12 14" src="https://github.com/user-attachments/assets/e89fb822-9957-4f23-b05a-3c636a322336">

### Priority

Low

### UI5 Web Components Version

2.2.0

### Browser

Chrome

### Operating System

Windows 11, macOS sonoma 14.6.1

### Additional Context

The issue is relevant for ui5-popover.

### Organization

SAP / UDEx components team

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

The issue is reproducible also for Windows.

Best Regards,
Lidiya

**Comment by PlutaKatarzyna** [comment]
Hi UI5 Team, just a quick notice that it's issue related with UDEx components. We are using ui5 components version 1.24.8 so we appreciate if fix could be down-ported.
Many Thanks!
Kate

**Comment by TeodorTaushanov** [comment]
Hello, the issues are fixed in the main and release-1.24 branches

**Comment by PlutaKatarzyna** [comment]
Hi @TeodorTaushanov @LidiyaGeorgieva ,
we update UI5 package version, and it seems that provided solution breaks position calculation with popover is nested inside element with css transform property. CSS transform property create it's own boundary that is treated kind of as new window. I assume that getBoundingClientRect method do not include parent transformation.

Current:
<img width="1792" alt="Image" src="https://github.com/user-attachments/assets/89a012fa-1d04-4b7b-93f3-189f5be2a33a" />

Without parent transform:
<img width="1300" alt="Image" src="https://github.com/user-attachments/assets/5a4bffb1-49cb-44e6-ae05-03d447c33b39" />

**Comment by TeodorTaushanov** [comment]
Hello @PlutaKatarzyna, where I can reproduce this issue?

**Comment by TeodorTaushanov** [comment]
Hi @PlutaKatarzyna, it appears that this issue is only present in version 1.24 and doesn't occur in version 2.x. For version 1.x of ui5-webcomponents, we advise against placing Popover/Dialog components within elements that have a transform value.

https://sap.github.io/ui5-webcomponents/v1/components/Popover/

**Note: ** We recommend placing popup-like components (ui5-dialog and ui5-popover) outside any other components. Preferably, the popup-like components should be placed in an upper level HTML element. Otherwise, in some cases the parent HTML elements can break the position and/or z-index management of the popup-like components.

Note: We don't recommend nesting popup-like components (ui5-dialog, ui5-popover).

**Comment by TeodorTaushanov** [comment]
Hello,

To summarize:

- The issue with "breaks position calculation when popover is nested inside an element with the CSS transform property" has been fixed.
- The RTL centering issue is fixed in 2.x, but not in 1.24 (the fix was reverted in 1.24 due to the aforementioned issue).
- The RTL arrow display issue is resolved in both 2.x and 1.24.
- We are unable to reproduce the "non-smooth transition" issue.

We'll comment here, when we have progress with the remaining issues. 


Best regards,
Teodor

**Comment by MaksymZahreba** [comment]
Hi @TeodorTaushanov  , 

Both the centering issue and arrow display issue for RTL display being broken while scrollbar present is still present for v1.X version and was not fixed. 
After discussion within the team was decided that due to migration to v2.X library and v1.X library not being supported anymore after that, while issues are absent in v2.X,  UDEx team will no longer pursue the fixing for mentioned issues, thus ticket may be closed.

Best regards, 
Maksym

**Comment by TeodorTaushanov** [comment]
@MaksymZahreba, in that case I'm closing the ticket
